/* TABLE */

CREATE TABLE category (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,

    name text NOT NULL UNIQUE,
    description text
);

/* FOREIGN KEYS */

/* TRIGGERS */

CREATE TRIGGER set_category_updated_at
    BEFORE UPDATE ON public.category
    FOR EACH ROW
    EXECUTE FUNCTION public.set_current_timestamp_updated_at();
